application: peerhealthexchangeorg
version: 1
runtime: python
api_version: 1

handlers:
- url: /_ah/mail/sms@peerhealthexchangeorg\.appspotmail\.com
  script: controller/handle_sms.py
- url: /
  script: controller/main.py

inbound_services:
- mail
